# Generated by Django 5.2.6 on 2025-10-03 02:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TarjetaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_tarjeta', models.CharField(editable=False, max_length=16, unique=True, validators=[django.core.validators.MinLengthValidator(16), django.core.validators.MaxLengthValidator(16)])),
                ('ultimos_4_digitos', models.CharField(editable=False, max_length=4, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(4)])),
                ('marca', models.CharField(choices=[('AMERICAN_EXPRESS', 'American Express'), ('CABAL', 'Cabal'), ('CREDICARD', 'Credicard')], default='CABAL', max_length=20)),
                ('cvc', models.CharField(editable=False, max_length=4, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(4)])),
                ('fecha_vencimiento', models.DateField(editable=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('BLOQUEADA', 'Bloqueada'), ('VENCIDA', 'Vencida'), ('CANCELADA', 'Cancelada')], default='ACTIVA', max_length=15)),
                ('limite_credito', models.DecimalField(decimal_places=2, default=50000.0, max_digits=15)),
                ('credito_disponible', models.DecimalField(decimal_places=2, default=50000.0, max_digits=15)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas_credito', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tarjeta de Crédito',
                'verbose_name_plural': 'Tarjetas de Crédito',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
