# Generated by Django 5.2.6 on 2025-10-03 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarjeta_credito', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjetacredito',
            name='marca',
            field=models.CharField(choices=[('CABAL', 'Cabal'), ('CREDICARD', 'Credicard')], default='CABAL', max_length=20),
        ),
    ]
