# Generated by Django 5.2.6 on 2025-10-09 21:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarjeta_credito', '0003_tarjetacredito_identificador_unico'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarjetacredito',
            options={'verbose_name': 'Tarjeta de Crédito', 'verbose_name_plural': 'Tarjetas de Crédito'},
        ),
        migrations.RemoveField(
            model_name='tarjetacredito',
            name='estado',
        ),
        migrations.AddField(
            model_name='tarjetacredito',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tarjetacredito',
            name='credito_disponible',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tarjetacredito',
            name='cvc',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='tarjetacredito',
            name='fecha_vencimiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tarjetacredito',
            name='identificador_unico',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tarjetacredito',
            name='limite_credito',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tarjetacredito',
            name='marca',
            field=models.CharField(choices=[('American Express', 'American Express'), ('Cabal', 'Cabal'), ('Credicard', 'Credicard')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tarjetacredito',
            name='numero_tarjeta',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='tarjetacredito',
            name='ultimos_4_digitos',
            field=models.CharField(max_length=4),
        ),
        migrations.CreateModel(
            name='TransaccionTarjeta',
            fields=[
                ('id_transaccion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('cobrada', 'Cobrada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('fecha_cobro', models.DateTimeField(blank=True, null=True)),
                ('numero_cuenta_destino', models.CharField(blank=True, max_length=20, null=True)),
                ('descripcion', models.TextField(blank=True)),
                ('tarjeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='tarjeta_credito.tarjetacredito')),
            ],
            options={
                'verbose_name': 'Transacción de Tarjeta',
                'verbose_name_plural': 'Transacciones de Tarjetas',
                'ordering': ['-fecha_pago'],
            },
        ),
    ]
