# Generated by Django 5.2.6 on 2025-10-09 21:32

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarjeta_credito', '0004_alter_tarjetacredito_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarjetacredito',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Tarjeta de Crédito', 'verbose_name_plural': 'Tarjetas de Crédito'},
        ),
        migrations.RemoveField(
            model_name='tarjetacredito',
            name='activa',
        ),
        migrations.AddField(
            model_name='tarjetacredito',
            name='estado',
            field=models.CharField(choices=[('ACTIVA', 'Activa'), ('BLOQUEADA', 'Bloqueada'), ('VENCIDA', 'Vencida'), ('CANCELADA', 'Cancelada')], default='ACTIVA', max_length=15),
        ),
        migrations.AlterField(
            model_name='tarjetacredito',
            name='credito_disponible',
            field=models.DecimalField(decimal_places=2, default=50000.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='tarjetacredito',
            name='cvc',
            field=models.CharField(editable=False, max_length=4, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(4)]),
        ),
        migrations.AlterField(
            model_name='tarjetacredito',
            name='fecha_vencimiento',
            field=models.DateField(editable=False),
        ),
        migrations.AlterField(
            model_name='tarjetacredito',
            name='identificador_unico',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único de la tarjeta para uso en APIs', unique=True),
        ),
        migrations.AlterField(
            model_name='tarjetacredito',
            name='limite_credito',
            field=models.DecimalField(decimal_places=2, default=50000.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='tarjetacredito',
            name='marca',
            field=models.CharField(choices=[('CABAL', 'Cabal'), ('CREDICARD', 'Credicard')], default='CABAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='tarjetacredito',
            name='numero_tarjeta',
            field=models.CharField(editable=False, max_length=16, unique=True, validators=[django.core.validators.MinLengthValidator(16), django.core.validators.MaxLengthValidator(16)]),
        ),
        migrations.AlterField(
            model_name='tarjetacredito',
            name='ultimos_4_digitos',
            field=models.CharField(editable=False, max_length=4, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(4)]),
        ),
    ]
